### ISSUE TITLE
初始化后再定位

### ISSUE THREAD

**Issue by Arthurcsh** [MengLiMing/MLMSegmentPage#4]
- (void)setSelectIndex:(NSInteger)index 可以再改造一下提供对外接口

- (void)setSelectIndex:(NSInteger)index {
    UIButton *indexButton = buttonArray[index];
    
    [self selectedHeadTitles:indexButton];
}

新增私有方法 - (void) segmentCurrentSelect:(NSInteger)index 代替原来的 - (void)setSelectIndex:(NSInteger)index

**Comment by MengLiMing** [comment]
已修改
